### ISSUE TITLE
Internal Error When Trying to Get Travel Times

### ISSUE THREAD

**Issue by cmerkle** [eifinger/pywaze#15]
I am attempting to get travel times between two locations in the northeaster US and am receiving the following error: 

```python
Traceback (most recent call last):
  File "c:\Users\clayt\OneDrive\Documents\Waze Travel Time\waze_get_travel_time_2.py", line 19, in <module>
    travel_time = asyncio.run(get_time(start, end))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Users\clayt\OneDrive\Documents\Waze Travel Time\waze_get_travel_time_2.py", line 11, in get_time
    results = await client.calc_all_routes_info(start, end)
  File "C:\Users\clayt\OneDrive\Documents\Waze Travel Time\env\lib\site-packages\pywaze\route_calculator.py", line 289, in calc_all_routes_info
    routes = await self.get_route(
  File "C:\Users\clayt\OneDrive\Documents\Waze Travel Time\env\lib\site-packages\pywaze\route_calculator.py", line 172, in get_route
    raise WRCError(response_json.get("error"))
pywaze.route_calculator.WRCError: Internal Error
```

My code is included below: 

```python
#!/usr/bin/env python3

import asyncio
from pywaze import route_calculator


async def get_time(start: str, end: str) -> float:
    """Return the travel time home."""

    async with route_calculator.WazeRouteCalculator() as client:
        results = await client.calc_all_routes_info(start, end)
        route_time, _ = list(results.values())[0]
        return route_time


start = "39.98025243,-74.1783464"
end = "40.8765308,-73.41253281"

travel_time = asyncio.run(get_time(start, end))

print(travel_time)
```

Note that I am able to successfully get a travel time using the "WazeRouteCalculator" repository from here:

https://github.com/kovacsbalu/WazeRouteCalculator

**Comment by cmerkle** [comment]
There were two issues that needed to be fixed to get this to work: first of all I had to set the region to US, and second I had to increase the timeout as 10 seconds was not enough. Recommend increasing the default timeout to something greater like 20 seconds.

**Comment by eifinger** [comment]
Thanks! I just checked, Wazeroutecalculator is using requests which does not have a timeout by default. pywaze uses httpx which does have a timeout. I will set it to 20s in HA

**Comment by cmerkle** [comment]
@eifinger thank you!! Note that I tried 20 seconds and it still didn't work. 30 works though. So maybe try 30s in HA.
